import:
	export GOPATH='/Users/xiangyu/Documents/git/Kademlia-in-Go/kademlia'

run:
	go install kademlia
	./bin/kademlia localhost:2334 localhost:2334

test:
	go install kademlia
	go test -race -v libkademlia
